# Generated by Django 5.2.11 on 2026-02-22 21:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20, verbose_name='status')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('current_period_start', models.DateTimeField(verbose_name='current period start')),
                ('current_period_end', models.DateTimeField(verbose_name='current period end')),
                ('trial_end_date', models.DateTimeField(blank=True, help_text='When the free trial ends', null=True, verbose_name='trial end date')),
                ('mpesa_shortcode', models.CharField(blank=True, help_text="Shop's M-Pesa collection number", max_length=20, verbose_name='M-Pesa paybill/till')),
                ('mpesa_account_reference', models.CharField(blank=True, help_text='Reference for M-Pesa payments', max_length=50, verbose_name='account reference')),
                ('next_billing_date', models.DateTimeField(verbose_name='next billing date')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='last payment date')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='auto renew')),
                ('is_locked', models.BooleanField(default=False, help_text='Lock access if payment fails', verbose_name='locked')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='shops.shop')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount (KES)')),
                ('payment_method', models.CharField(choices=[('MPESA_B2B', 'M-Pesa Business'), ('MPESA_C2B', 'M-Pesa Customer'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], default='MPESA_B2B', max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='status')),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=50, null=True, unique=True, verbose_name='M-Pesa receipt')),
                ('mpesa_phone_number', models.CharField(blank=True, help_text='Phone number used for payment', max_length=20, verbose_name='phone number')),
                ('mpesa_request_id', models.CharField(blank=True, help_text='Internal M-Pesa API request ID', max_length=100, verbose_name='request ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='payment date')),
                ('period_start', models.DateTimeField(verbose_name='period start')),
                ('period_end', models.DateTimeField(verbose_name='period end')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store M-Pesa callback data', verbose_name='metadata')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Has this payment been verified?', verbose_name='reconciled')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='reconciled at')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscription')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='invoice number')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='issue date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Kenya VAT rate', max_digits=5, verbose_name='VAT rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT amount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='subscription.payment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscription.subscription')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-issue_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='plan name')),
                ('plan_type', models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20, verbose_name='plan type')),
                ('billing_period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly (Fortnightly)'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20, verbose_name='billing period')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Kenya Shillings', max_digits=10, verbose_name='price (KES)')),
                ('max_users', models.PositiveIntegerField(default=1, help_text='Maximum staff accounts allowed', verbose_name='max users')),
                ('max_printing_machines', models.PositiveIntegerField(default=1, help_text='Maximum printing machines (Digital, Large Format, Offset). 0 = unlimited', verbose_name='max printing machines')),
                ('max_finishing_machines', models.PositiveIntegerField(default=0, help_text='Maximum finishing equipment. 0 = none allowed', verbose_name='max finishing machines')),
                ('max_quotes_per_month', models.PositiveIntegerField(default=100, help_text='Maximum quotes per month. 0 = unlimited', verbose_name='max quotes/month')),
                ('max_products', models.PositiveIntegerField(default=50, help_text='Maximum product templates. 0 = unlimited', verbose_name='max products')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='API access')),
                ('has_bulk_operations', models.BooleanField(default=False, verbose_name='bulk operations')),
                ('has_custom_branding', models.BooleanField(default=False, verbose_name='custom branding')),
                ('has_priority_support', models.BooleanField(default=False, verbose_name='priority support')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'ordering': ['price'],
                'constraints': [models.UniqueConstraint(fields=('plan_type', 'billing_period'), name='unique_plan_per_type_period')],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='MpesaStkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount (KES)')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, help_text='From Daraja STK push response', max_length=100, verbose_name='checkout request ID')),
                ('merchant_request_id', models.CharField(blank=True, help_text='From Daraja STK push response', max_length=100, verbose_name='merchant request ID')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], db_index=True, default='INITIATED', max_length=20, verbose_name='status')),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='Filled on success callback', max_length=50, verbose_name='M-Pesa receipt')),
                ('raw_request_payload', models.JSONField(blank=True, default=dict, help_text='Original STK push request payload', verbose_name='raw request')),
                ('raw_callback_payload', models.JSONField(blank=True, default=dict, help_text='Callback payload from Daraja', verbose_name='raw callback')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_stk_requests', to='subscription.subscriptionplan')),
            ],
            options={
                'verbose_name': 'M-Pesa STK request',
                'verbose_name_plural': 'M-Pesa STK requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mpesa_receipt_number'], name='subscriptio_mpesa_r_99060c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='subscriptio_status_d4f228_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesastkrequest',
            index=models.Index(fields=['checkout_request_id'], name='subscriptio_checkou_cfb445_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesastkrequest',
            index=models.Index(fields=['status', 'created_at'], name='subscriptio_status_a693f4_idx'),
        ),
    ]
