# Generated by Django 5.2.4 on 2026-02-16 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_finishing_machines',
            field=models.PositiveIntegerField(default=0, help_text='Maximum finishing equipment. 0 = none allowed', verbose_name='max finishing machines'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_printing_machines',
            field=models.PositiveIntegerField(default=1, help_text='Maximum printing machines (Digital, Large Format, Offset). 0 = unlimited', verbose_name='max printing machines'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='MpesaStkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount (KES)')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, help_text='From Daraja STK push response', max_length=100, verbose_name='checkout request ID')),
                ('merchant_request_id', models.CharField(blank=True, help_text='From Daraja STK push response', max_length=100, verbose_name='merchant request ID')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], db_index=True, default='INITIATED', max_length=20, verbose_name='status')),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='Filled on success callback', max_length=50, verbose_name='M-Pesa receipt')),
                ('raw_request_payload', models.JSONField(blank=True, default=dict, help_text='Original STK push request payload', verbose_name='raw request')),
                ('raw_callback_payload', models.JSONField(blank=True, default=dict, help_text='Callback payload from Daraja', verbose_name='raw callback')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_stk_requests', to='subscription.subscriptionplan')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa STK request',
                'verbose_name_plural': 'M-Pesa STK requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['checkout_request_id'], name='subscriptio_checkou_cfb445_idx'), models.Index(fields=['status', 'created_at'], name='subscriptio_status_a693f4_idx')],
            },
        ),
    ]
