# Generated by Django 5.2 on 2026-02-08 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='shop name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('business_email', models.EmailField(help_text='Public contact email.', max_length=254, verbose_name='business email')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='phone number')),
                ('address_line', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state/province')),
                ('zip_code', models.CharField(max_length=20, verbose_name='zip/postal code')),
                ('country', models.CharField(default='USA', max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this shop has been verified via claim.', verbose_name='verified')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this shop is visible/active.', verbose_name='active')),
                ('owner', models.ForeignKey(help_text='The primary owner of the shop account.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], db_index=True, verbose_name='weekday')),
                ('from_hour', models.TimeField(blank=True, null=True, verbose_name='opening time')),
                ('to_hour', models.TimeField(blank=True, null=True, verbose_name='closing time')),
                ('is_closed', models.BooleanField(default=False, verbose_name='closed')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='shops.shop')),
            ],
            options={
                'verbose_name': 'opening hour',
                'verbose_name_plural': 'opening hours',
                'ordering': ['weekday', 'from_hour'],
            },
        ),
        migrations.CreateModel(
            name='ShopClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business_name', models.CharField(help_text='Name of the business as stated in the claim.', max_length=255, verbose_name='business name')),
                ('business_email', models.EmailField(help_text='The corporate email used for verification.', max_length=254, verbose_name='business email')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified / Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='verification token')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes regarding this claim.', verbose_name='admin notes')),
                ('shop', models.ForeignKey(blank=True, help_text='The existing shop being claimed, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='shops.shop')),
                ('user', models.ForeignKey(help_text='The user submitting the claim.', on_delete=django.db.models.deletion.CASCADE, related_name='shop_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shop claim',
                'verbose_name_plural': 'shop claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('DESIGNER', 'Designer')], default='STAFF', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user has active access to the shop.', verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shop member',
                'verbose_name_plural': 'shop members',
            },
        ),
        migrations.CreateModel(
            name='ShopSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('website', 'Official Website'), ('other', 'Other')], max_length=20, verbose_name='platform')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('username', models.CharField(blank=True, help_text='Optional handle for display.', max_length=100, verbose_name='username/handle')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='shops.shop')),
            ],
            options={
                'verbose_name': 'shop social link',
                'verbose_name_plural': 'shop social links',
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['name', 'city'], name='shops_shop_name_6cc88f_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='shops_shop_latitud_e4840a_idx'),
        ),
        migrations.AddConstraint(
            model_name='openinghours',
            constraint=models.UniqueConstraint(fields=('shop', 'weekday', 'from_hour'), name='unique_shop_daily_hours'),
        ),
        migrations.AddConstraint(
            model_name='shopmember',
            constraint=models.UniqueConstraint(fields=('shop', 'user'), name='unique_shop_membership'),
        ),
        migrations.AddConstraint(
            model_name='shopsociallink',
            constraint=models.UniqueConstraint(fields=('shop', 'platform'), name='unique_shop_social_platform'),
        ),
    ]
