# Generated by Django 5.2.11 on 2026-02-22 21:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('pricing', '0001_initial'),
        ('shops', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('defaults', models.JSONField(default=dict, help_text='Default settings: {width, height, gsm, sides, finishing_ids}')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='shops.shop')),
                ('template', models.ForeignKey(blank=True, help_text='PrintTemplate for dimensions/options. Null = use defaults only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_presets', to='templates.printtemplate')),
            ],
            options={
                'verbose_name': 'product template',
                'verbose_name_plural': 'product templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated, e.g., Q-202602-0001', max_length=50, verbose_name='reference')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('SENT', 'Sent to Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to Job')], default='DRAFT', max_length=20)),
                ('customer_notes', models.TextField(blank=True, verbose_name='customer notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='tax rate %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='discount')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='grand total')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='shops.shop')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='templates.printtemplate')),
                ('user', models.ForeignKey(help_text='The customer requesting the quote', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Business Cards', max_length=150, verbose_name='item name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('calculated_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total price')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'quote item',
                'verbose_name_plural': 'quote items',
            },
        ),
        migrations.CreateModel(
            name='QuoteItemFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('calculated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='cost')),
                ('finishing_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.finishingservice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing', to='quotes.quoteitem')),
            ],
            options={
                'verbose_name': 'quote item finishing',
                'verbose_name_plural': 'quote item finishings',
            },
        ),
        migrations.CreateModel(
            name='QuoteItemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Cover, Inner Pages', max_length=100, verbose_name='part name')),
                ('final_width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='width (mm)')),
                ('final_height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='height (mm)')),
                ('print_sides', models.CharField(choices=[('SINGLE', 'Single-sided'), ('DOUBLE', 'Double-sided')], default='SINGLE', max_length=10, verbose_name='print sides')),
                ('items_per_sheet', models.PositiveIntegerField(default=1, help_text='How many fit on one sheet', verbose_name='items per sheet')),
                ('total_sheets_required', models.PositiveIntegerField(default=0, verbose_name='sheets required')),
                ('part_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='cost')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quotes.quoteitem')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.machine')),
                ('paper', models.ForeignKey(blank=True, help_text='Paper to use (dimensions + price from this record)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_item_parts', to='inventory.paper')),
            ],
            options={
                'verbose_name': 'quote item part',
                'verbose_name_plural': 'quote item parts',
            },
        ),
    ]
