# Generated by Django 5.2 on 2026-01-25 20:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('pricing', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('defaults', models.JSONField(default=dict, help_text='JSON Config for default selection')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated Ref ID', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Job')], default='DRAFT', max_length=20)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g. Annual Reports', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('calculated_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteItemFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('calculated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('finishing_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.finishingprice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing', to='quotes.quoteitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteItemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g. Cover, Inner Pages', max_length=100)),
                ('final_width', models.DecimalField(decimal_places=2, help_text='Width in mm', max_digits=10)),
                ('final_height', models.DecimalField(decimal_places=2, help_text='Height in mm', max_digits=10)),
                ('print_sides', models.CharField(choices=[('SIMPLEX', 'Simplex (One Side)'), ('DUPLEX', 'Duplex (Two Sides)')], default='SIMPLEX', max_length=10)),
                ('items_per_sheet', models.PositiveIntegerField(default=1, help_text='N-Up on the stock sheet')),
                ('total_sheets_required', models.PositiveIntegerField(default=0, help_text='Total large sheets needed for the run')),
                ('part_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quotes.quoteitem')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.machine')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('preferred_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.materialstock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
