# Generated by Django 5.2 on 2026-02-04 21:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        ('templates', '0002_alter_templatecategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttemplate',
            options={'ordering': ['name'], 'verbose_name': 'product template', 'verbose_name_plural': 'product templates'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'quote', 'verbose_name_plural': 'quotes'},
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Special instructions from the customer', verbose_name='customer notes'),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='quote',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notes visible only to shop staff', verbose_name='internal notes'),
        ),
        migrations.AddField(
            model_name='quote',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='The gallery template this quote was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='templates.printtemplate'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='VAT rate percentage', max_digits=5, verbose_name='tax rate'),
        ),
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, help_text='Brief description of the quote', max_length=200, verbose_name='quote title'),
        ),
        migrations.AddField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Quote expiration date', null=True, verbose_name='valid until'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('SENT', 'Sent to Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to Job')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(help_text='The customer requesting the quote', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
