# Generated by Django 5.2 on 2026-02-08 20:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Bulk Order 10% Off', max_length=100, verbose_name='name')),
                ('min_quantity', models.PositiveIntegerField(default=100, help_text='Minimum sheets/items to qualify', verbose_name='minimum quantity')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Percentage discount (e.g., 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='discount %')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_discounts', to='shops.shop')),
            ],
            options={
                'verbose_name': 'volume discount',
                'verbose_name_plural': 'volume discounts',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='FinishingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Matt Lamination A3, Spiral Binding', max_length=100, verbose_name='service name')),
                ('category', models.CharField(choices=[('LAMINATION', 'Lamination'), ('BINDING', 'Binding'), ('CUTTING', 'Cutting'), ('FOLDING', 'Folding'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='category')),
                ('charge_by', models.CharField(choices=[('PER_SHEET', 'Per Sheet'), ('PER_PIECE', 'Per Piece/Item'), ('PER_JOB', 'Per Job (Flat Fee)')], default='PER_SHEET', max_length=20, verbose_name='charge by')),
                ('buying_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Your cost (if any)', max_digits=10, verbose_name='buying price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price customer pays', max_digits=10, verbose_name='selling price')),
                ('is_default', models.BooleanField(default=False, help_text='Pre-select this option for customers', verbose_name='selected by default')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_services', to='shops.shop')),
            ],
            options={
                'verbose_name': 'finishing service',
                'verbose_name_plural': 'finishing services',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'name'), name='unique_finishing_service')],
            },
        ),
        migrations.CreateModel(
            name='PaperPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], default='A3', max_length=20, verbose_name='paper size')),
                ('gsm', models.PositiveIntegerField(help_text='Paper weight: 80, 130, 150, 200, 300, etc.', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(500)], verbose_name='GSM (weight)')),
                ('paper_type', models.CharField(choices=[('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('BOND', 'Bond'), ('ART', 'Art Paper')], default='GLOSS', max_length=20, verbose_name='paper type')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='What YOU pay per sheet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='buying price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='What CUSTOMER pays per sheet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='selling price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'paper price',
                'verbose_name_plural': 'paper prices',
                'ordering': ['sheet_size', 'gsm'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'sheet_size', 'gsm', 'paper_type'), name='unique_paper_price')],
            },
        ),
        migrations.CreateModel(
            name='PrintingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], default='A4', max_length=20, verbose_name='paper size')),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Full Color')], default='COLOR', max_length=20, verbose_name='color')),
                ('selling_price_per_side', models.DecimalField(decimal_places=2, help_text='Price customer pays per printed side', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='selling price per side')),
                ('buying_price_per_side', models.DecimalField(blank=True, decimal_places=2, help_text='Your cost per side (optional, for tracking profit)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='buying price per side')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('machine', models.ForeignKey(help_text='Which machine/printer', on_delete=django.db.models.deletion.PROTECT, related_name='printing_prices', to='inventory.machine')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'printing price',
                'verbose_name_plural': 'printing prices',
                'ordering': ['sheet_size', 'color_mode'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'machine', 'sheet_size', 'color_mode'), name='unique_printing_price')],
            },
        ),
    ]
