# Generated by Django 5.2 on 2026-01-25 18:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('process_name', models.CharField(help_text="e.g., 'Matt Lamination SRA3', 'Saddle Stitch Binding'", max_length=150, verbose_name='process name')),
                ('category', models.CharField(choices=[('LAMINATION', 'Lamination'), ('BINDING', 'Binding'), ('CUTTING', 'Cutting'), ('CREASING', 'Creasing/Scoring'), ('FOLDING', 'Folding'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='category')),
                ('unit', models.CharField(choices=[('PER_SHEET', 'Per Sheet'), ('PER_SIDE', 'Per Side (For Lamination)'), ('PER_JOB', 'Per Job (Flat Fee)'), ('PER_PIECE', 'Per Finished Item'), ('PER_BATCH', 'Per Batch')], default='PER_SHEET', max_length=20, verbose_name='pricing unit')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price per unit.', max_digits=10, verbose_name='price')),
                ('batch_size', models.PositiveIntegerField(default=1, help_text="If unit is 'Per Batch', define size (e.g., 1000 for 'per 1000 sheets').", verbose_name='batch size')),
                ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='One-time setup fee.', max_digits=10, verbose_name='setup fee')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1, verbose_name='minimum order quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'finishing price',
                'verbose_name_plural': 'finishing prices',
                'ordering': ['category', 'process_name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('pricing_method', models.CharField(choices=[('FIXED', 'Fixed Price'), ('MARKUP', 'Markup on Cost'), ('MARGIN', 'Profit Margin')], default='FIXED', max_length=20, verbose_name='pricing method')),
                ('selling_price_per_unit', models.DecimalField(blank=True, decimal_places=4, help_text='Fixed selling price. Required if pricing method is FIXED.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='selling price per unit')),
                ('markup_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Markup percentage on cost price (e.g., 50 for 50%). Used if method is MARKUP.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))], verbose_name='markup percentage')),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Target profit margin (e.g., 30 for 30%). Used if method is MARGIN.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='margin percentage')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum charge for this material.', max_digits=10, verbose_name='minimum order value')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('material', models.ForeignKey(help_text='The material this price applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='selling_prices', to='inventory.material')),
                ('shop', models.ForeignKey(help_text='The shop this pricing belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='material_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'material price',
                'verbose_name_plural': 'material prices',
                'ordering': ['material__name'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Start of the quantity range.', verbose_name='min quantity')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='End of the quantity range. Leave blank for unlimited (e.g., 100+).', null=True, verbose_name='max quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='The rate applied within this range.', max_digits=10, verbose_name='price per unit')),
                ('finishing_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pricing.finishingprice')),
            ],
            options={
                'verbose_name': 'pricing tier',
                'verbose_name_plural': 'pricing tiers',
                'ordering': ['finishing_service', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text="e.g., 'Bulk Print Discount', '500+ Sheets'", max_length=100, verbose_name='discount name')),
                ('minimum_quantity', models.PositiveIntegerField(help_text='Minimum quantity to trigger this discount.', verbose_name='minimum quantity')),
                ('maximum_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity for this tier. Leave blank for unlimited.', null=True, verbose_name='maximum quantity')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Off'), ('FIXED_RATE', 'Fixed Rate Override'), ('AMOUNT_OFF', 'Fixed Amount Off')], default='PERCENTAGE', max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage, fixed rate, or amount based on discount type.', max_digits=10, verbose_name='discount value')),
                ('applies_to_print', models.BooleanField(default=True, verbose_name='applies to print')),
                ('applies_to_material', models.BooleanField(default=False, verbose_name='applies to material')),
                ('applies_to_finishing', models.BooleanField(default=False, verbose_name='applies to finishing')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_discounts', to='shops.shop')),
            ],
            options={
                'verbose_name': 'volume discount',
                'verbose_name_plural': 'volume discounts',
                'ordering': ['minimum_quantity'],
            },
        ),
        migrations.CreateModel(
            name='DigitalPrintPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('A3', 'A3 (297 x 420 mm)'), ('SRA3', 'SRA3 (320 x 450 mm)'), ('SRA4', 'SRA4 (225 x 320 mm)'), ('A5', 'A5 (148 x 210 mm)'), ('LETTER', 'Letter (8.5 x 11 in)'), ('LEGAL', 'Legal (8.5 x 14 in)'), ('TABLOID', 'Tabloid (11 x 17 in)')], default='A4', max_length=20, verbose_name='sheet size')),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Full Color'), ('SPOT', 'Spot Color')], default='COLOR', max_length=20, verbose_name='color mode')),
                ('click_rate', models.DecimalField(decimal_places=2, help_text='Cost per impression/click (one side of paper).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='click rate')),
                ('duplex_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional rate for double-sided printing. If null, defaults to 2x click_rate.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='duplex rate')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1, help_text='Minimum number of impressions for this rate.', verbose_name='minimum order quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('machine', models.ForeignKey(help_text='The machine this price applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='print_prices', to='inventory.machine')),
                ('shop', models.ForeignKey(help_text='The shop this pricing belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='digital_print_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'digital print price',
                'verbose_name_plural': 'digital print prices',
                'ordering': ['machine__name', 'sheet_size'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'machine', 'sheet_size', 'color_mode'), name='unique_print_price_per_shop_machine_size_color')],
            },
        ),
        migrations.AddConstraint(
            model_name='finishingprice',
            constraint=models.UniqueConstraint(fields=('shop', 'process_name'), name='unique_finishing_price_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='materialprice',
            constraint=models.UniqueConstraint(fields=('shop', 'material'), name='unique_material_price_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.UniqueConstraint(fields=('finishing_service', 'min_quantity'), name='unique_tier_start_per_service'),
        ),
    ]
