# Generated by Django 5.2.4 on 2026-02-22 11:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFinishingServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Matt Lamination A3, Spiral Binding', max_length=100)),
                ('unit_type', models.CharField(choices=[('PER_SHEET', 'Per Sheet'), ('PER_PIECE', 'Per Piece/Item'), ('PER_JOB', 'Per Job (Flat Fee)')], default='PER_SHEET', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'default finishing service template',
                'verbose_name_plural': 'default finishing service templates',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'unit_type'), name='unique_default_finishing_template')],
            },
        ),
        migrations.CreateModel(
            name='DefaultMaterialPriceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('material_type', models.CharField(choices=[('VINYL', 'Vinyl'), ('BANNER', 'Banner'), ('CANVAS', 'Canvas'), ('PAPER', 'Paper'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('unit', models.CharField(choices=[('SQM', 'Square Meter'), ('SHEET', 'Per Sheet')], default='SQM', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'default material price template',
                'verbose_name_plural': 'default material price templates',
                'ordering': ['material_type', 'unit'],
                'constraints': [models.UniqueConstraint(fields=('material_type', 'unit'), name='unique_default_material_template')],
            },
        ),
        migrations.CreateModel(
            name='DefaultPaperPriceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], default='A3', max_length=20)),
                ('paper_type', models.CharField(choices=[('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('BOND', 'Bond'), ('ART', 'Art Paper')], default='GLOSS', max_length=20)),
                ('gsm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(500)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'default paper price template',
                'verbose_name_plural': 'default paper price templates',
                'ordering': ['sheet_size', 'gsm', 'paper_type'],
                'constraints': [models.UniqueConstraint(fields=('sheet_size', 'paper_type', 'gsm'), name='unique_default_paper_template')],
            },
        ),
        migrations.CreateModel(
            name='DefaultPrintingPriceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('machine_category', models.CharField(help_text='Matches Machine.machine_type: DIGITAL, LARGE_FORMAT, OFFSET', max_length=20, verbose_name='machine category/type')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], default='A4', max_length=20)),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Full Color')], default='COLOR', max_length=20)),
                ('selling_price_per_side', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='selling price per side')),
                ('selling_price_duplex_per_sheet', models.DecimalField(blank=True, decimal_places=2, help_text='Override for double-sided. If null, uses 2× per-side.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='selling price duplex per sheet')),
            ],
            options={
                'verbose_name': 'default printing price template',
                'verbose_name_plural': 'default printing price templates',
                'ordering': ['machine_category', 'sheet_size', 'color_mode'],
                'constraints': [models.UniqueConstraint(fields=('machine_category', 'sheet_size', 'color_mode'), name='unique_default_printing_template')],
            },
        ),
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Bulk Order 10% Off', max_length=100, verbose_name='name')),
                ('min_quantity', models.PositiveIntegerField(default=100, help_text='Minimum sheets/items to qualify', verbose_name='minimum quantity')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Percentage discount (e.g., 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='discount %')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_discounts', to='shops.shop')),
            ],
            options={
                'verbose_name': 'volume discount',
                'verbose_name_plural': 'volume discounts',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='FinishingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Matt Lamination A3, Spiral Binding', max_length=100, verbose_name='service name')),
                ('category', models.CharField(choices=[('LAMINATION', 'Lamination'), ('BINDING', 'Binding'), ('CUTTING', 'Cutting'), ('FOLDING', 'Folding'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='category')),
                ('charge_by', models.CharField(choices=[('PER_SHEET', 'Per Sheet'), ('PER_PIECE', 'Per Piece/Item'), ('PER_JOB', 'Per Job (Flat Fee)')], default='PER_SHEET', max_length=20, verbose_name='charge by')),
                ('buying_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Your cost (if any)', max_digits=10, verbose_name='buying price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price customer pays', max_digits=10, verbose_name='selling price')),
                ('is_default', models.BooleanField(default=False, help_text='Pre-select this option for customers', verbose_name='selected by default')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default_seeded', models.BooleanField(default=False, verbose_name='default seeded')),
                ('needs_review', models.BooleanField(default=False, verbose_name='needs review')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_services', to='shops.shop')),
            ],
            options={
                'verbose_name': 'finishing service',
                'verbose_name_plural': 'finishing services',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'name'), name='unique_finishing_service')],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('material_type', models.CharField(choices=[('BANNER', 'Banner'), ('VINYL', 'Vinyl'), ('REFLECTIVE', 'Reflective'), ('CANVAS', 'Canvas'), ('PAPER', 'Paper'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='material type')),
                ('unit', models.CharField(choices=[('SHEET_A4', 'Sheet A4'), ('SHEET_A3', 'Sheet A3'), ('SHEET_SRA3', 'Sheet SRA3'), ('SHEET', 'Per Sheet'), ('SQM', 'Per Square Metre')], default='SQM', max_length=20, verbose_name='unit')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='What CUSTOMER pays per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='selling price')),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, help_text='What YOU pay per unit (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='buying price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default_seeded', models.BooleanField(default=False, verbose_name='default seeded')),
                ('needs_review', models.BooleanField(default=False, verbose_name='needs review')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'material price',
                'verbose_name_plural': 'material prices',
                'ordering': ['material_type', 'unit'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'material_type', 'unit'), name='unique_material_price')],
            },
        ),
        migrations.CreateModel(
            name='PaperPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], default='A3', max_length=20, verbose_name='paper size')),
                ('gsm', models.PositiveIntegerField(help_text='Paper weight: 80, 130, 150, 200, 300, etc.', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(500)], verbose_name='GSM (weight)')),
                ('paper_type', models.CharField(choices=[('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('BOND', 'Bond'), ('ART', 'Art Paper')], default='GLOSS', max_length=20, verbose_name='paper type')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='What YOU pay per sheet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='buying price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='What CUSTOMER pays per sheet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='selling price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default_seeded', models.BooleanField(default=False, verbose_name='default seeded')),
                ('needs_review', models.BooleanField(default=False, verbose_name='needs review')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'paper price',
                'verbose_name_plural': 'paper prices',
                'ordering': ['sheet_size', 'gsm'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'sheet_size', 'gsm', 'paper_type'), name='unique_paper_price')],
            },
        ),
        migrations.CreateModel(
            name='PrintingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], default='A4', max_length=20, verbose_name='paper size')),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Full Color')], default='COLOR', max_length=20, verbose_name='color')),
                ('selling_price_per_side', models.DecimalField(decimal_places=2, help_text='Price customer pays per printed side', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='selling price per side')),
                ('selling_price_duplex_per_sheet', models.DecimalField(blank=True, decimal_places=2, help_text='Override for double-sided: price per sheet (both sides). If null, uses 2× per-side.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='selling price duplex per sheet')),
                ('buying_price_per_side', models.DecimalField(blank=True, decimal_places=2, help_text='Your cost per side (optional, for tracking profit)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='buying price per side')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default_seeded', models.BooleanField(default=False, verbose_name='default seeded')),
                ('needs_review', models.BooleanField(default=False, verbose_name='needs review')),
                ('machine', models.ForeignKey(help_text='Which machine/printer', on_delete=django.db.models.deletion.PROTECT, related_name='printing_prices', to='inventory.machine')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'printing price',
                'verbose_name_plural': 'printing prices',
                'ordering': ['sheet_size', 'color_mode'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'machine', 'sheet_size', 'color_mode'), name='unique_printing_price')],
            },
        ),
    ]
