# Generated by Django 5.2 on 2026-02-02 21:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('process_name', models.CharField(max_length=100, verbose_name='process name')),
                ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='setup fee')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit cost')),
            ],
            options={
                'verbose_name': 'finishing option',
                'verbose_name_plural': 'finishing options',
                'ordering': ['process_name'],
            },
        ),
        migrations.CreateModel(
            name='PricingVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Digital Print Margin', max_length=100, verbose_name='name')),
                ('key', models.SlugField(help_text='Unique identifier, e.g. global-margin', max_length=100, unique=True, verbose_name='key')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='value')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'pricing variable',
                'verbose_name_plural': 'pricing variables',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('material_type', models.CharField(max_length=100, verbose_name='material type')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost per unit')),
                ('unit_measure', models.CharField(choices=[('m2', 'Square Meter'), ('sheet', 'Sheet')], max_length=20, verbose_name='unit measure')),
            ],
            options={
                'verbose_name': 'raw material',
                'verbose_name_plural': 'raw materials',
                'ordering': ['material_type'],
            },
        ),
        migrations.CreateModel(
            name='PricingEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product_name', models.CharField(max_length=255, verbose_name='product name')),
                ('finishes', models.ManyToManyField(blank=True, related_name='pricing_engines', to='pricing.finishingoption', verbose_name='finishes')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_engines', to='pricing.rawmaterial')),
            ],
            options={
                'verbose_name': 'pricing engine',
                'verbose_name_plural': 'pricing engines',
                'ordering': ['product_name'],
            },
        ),
    ]
