# Generated by Django 5.2 on 2026-02-04 21:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_finishingoption_pricingvariable_rawmaterial_and_more'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperGSMPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('A3', 'A3 (297 x 420 mm)'), ('SRA3', 'SRA3 (320 x 450 mm)'), ('SRA4', 'SRA4 (225 x 320 mm)'), ('A5', 'A5 (148 x 210 mm)'), ('LETTER', 'Letter (8.5 x 11 in)'), ('LEGAL', 'Legal (8.5 x 14 in)'), ('TABLOID', 'Tabloid (11 x 17 in)')], default='A3', help_text='Paper size this price applies to.', max_length=20, verbose_name='sheet size')),
                ('gsm', models.PositiveIntegerField(help_text='Paper weight in grams per square meter (e.g., 130, 150, 200, 300).', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(500)], verbose_name='GSM (paper weight)')),
                ('paper_type', models.CharField(default='Gloss', help_text='Type of paper (e.g., Gloss, Matte, Bond, Art Paper).', max_length=100, verbose_name='paper type')),
                ('price_per_sheet', models.DecimalField(decimal_places=2, help_text='Customer price per sheet for this GSM paper.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per sheet')),
                ('cost_per_sheet', models.DecimalField(blank=True, decimal_places=2, help_text='Your cost price (optional, for profit tracking).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cost per sheet')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(help_text='The shop this pricing belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='paper_gsm_prices', to='shops.shop')),
            ],
            options={
                'verbose_name': 'paper price (GSM)',
                'verbose_name_plural': 'paper prices (GSM)',
                'ordering': ['sheet_size', 'gsm'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'sheet_size', 'gsm', 'paper_type'), name='unique_paper_price_per_shop_size_gsm_type')],
            },
        ),
    ]
