# Generated by Django 5.2

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_add_duplex_and_material_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingprice',
            name='is_default_seeded',
            field=models.BooleanField(default=False, verbose_name='default seeded'),
        ),
        migrations.AddField(
            model_name='printingprice',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.AddField(
            model_name='paperprice',
            name='is_default_seeded',
            field=models.BooleanField(default=False, verbose_name='default seeded'),
        ),
        migrations.AddField(
            model_name='paperprice',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.AddField(
            model_name='finishingservice',
            name='is_default_seeded',
            field=models.BooleanField(default=False, verbose_name='default seeded'),
        ),
        migrations.AddField(
            model_name='finishingservice',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.AddField(
            model_name='materialprice',
            name='is_default_seeded',
            field=models.BooleanField(default=False, verbose_name='default seeded'),
        ),
        migrations.AddField(
            model_name='materialprice',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='needs review'),
        ),
        migrations.CreateModel(
            name='DefaultPrintingPriceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('machine_category', models.CharField(help_text='Matches Machine.machine_type: DIGITAL, LARGE_FORMAT, OFFSET', max_length=20, verbose_name='machine category/type')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], default='A4', max_length=20)),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Full Color')], default='COLOR', max_length=20)),
                ('selling_price_per_side', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='selling price per side')),
                ('selling_price_duplex_per_sheet', models.DecimalField(blank=True, decimal_places=2, help_text='Override for double-sided. If null, uses 2× per-side.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='selling price duplex per sheet')),
            ],
            options={
                'verbose_name': 'default printing price template',
                'verbose_name_plural': 'default printing price templates',
                'ordering': ['machine_category', 'sheet_size', 'color_mode'],
            },
        ),
        migrations.AddConstraint(
            model_name='defaultprintingpricetemplate',
            constraint=models.UniqueConstraint(fields=('machine_category', 'sheet_size', 'color_mode'), name='unique_default_printing_template'),
        ),
        migrations.CreateModel(
            name='DefaultPaperPriceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], default='A3', max_length=20)),
                ('paper_type', models.CharField(choices=[('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('BOND', 'Bond'), ('ART', 'Art Paper')], default='GLOSS', max_length=20)),
                ('gsm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(500)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'default paper price template',
                'verbose_name_plural': 'default paper price templates',
                'ordering': ['sheet_size', 'gsm', 'paper_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='defaultpaperpricetemplate',
            constraint=models.UniqueConstraint(fields=('sheet_size', 'paper_type', 'gsm'), name='unique_default_paper_template'),
        ),
        migrations.CreateModel(
            name='DefaultMaterialPriceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('material_type', models.CharField(choices=[('VINYL', 'Vinyl'), ('BANNER', 'Banner'), ('CANVAS', 'Canvas'), ('PAPER', 'Paper'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('unit', models.CharField(choices=[('SQM', 'Square Meter'), ('SHEET', 'Per Sheet')], default='SQM', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'default material price template',
                'verbose_name_plural': 'default material price templates',
                'ordering': ['material_type', 'unit'],
            },
        ),
        migrations.AddConstraint(
            model_name='defaultmaterialpricetemplate',
            constraint=models.UniqueConstraint(fields=('material_type', 'unit'), name='unique_default_material_template'),
        ),
        migrations.CreateModel(
            name='DefaultFinishingServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Matt Lamination A3, Spiral Binding', max_length=100)),
                ('unit_type', models.CharField(choices=[('PER_SHEET', 'Per Sheet'), ('PER_PIECE', 'Per Piece/Item'), ('PER_JOB', 'Per Job (Flat Fee)')], default='PER_SHEET', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'default finishing service template',
                'verbose_name_plural': 'default finishing service templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='defaultfinishingservicetemplate',
            constraint=models.UniqueConstraint(fields=('name', 'unit_type'), name='unique_default_finishing_template'),
        ),
    ]
