# Generated by Django 6.0.2 on 2026-02-22 05:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_add_templates_and_seeding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialprice',
            name='material_type',
            field=models.CharField(choices=[('BANNER', 'Banner'), ('VINYL', 'Vinyl'), ('REFLECTIVE', 'Reflective'), ('CANVAS', 'Canvas'), ('PAPER', 'Paper'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='material type'),
        ),
        migrations.AlterField(
            model_name='materialprice',
            name='unit',
            field=models.CharField(choices=[('SHEET_A4', 'Sheet A4'), ('SHEET_A3', 'Sheet A3'), ('SHEET_SRA3', 'Sheet SRA3'), ('SHEET', 'Per Sheet'), ('SQM', 'Per Square Metre')], default='SQM', max_length=20, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='printingprice',
            name='selling_price_duplex_per_sheet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override for double-sided: price per sheet (both sides). If null, uses 2× per-side.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='selling price duplex per sheet'),
        ),
    ]
