# Generated by Django 5.2 on 2026-02-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_add_paper_gsm_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingprice',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the finishing process for customers', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='finishingprice',
            name='is_default_selected',
            field=models.BooleanField(default=False, help_text='If true, this is pre-selected for optional finishing', verbose_name='default selected'),
        ),
        migrations.AddField(
            model_name='finishingprice',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='If true, this finishing is always applied to applicable jobs', verbose_name='mandatory'),
        ),
    ]
