# Generated by Django 5.2.4 on 2026-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author_name', models.CharField(max_length=150, verbose_name='author name')),
                ('author_role', models.CharField(blank=True, max_length=150, verbose_name='author role / company')),
                ('quote', models.TextField(help_text='The testimonial text.', verbose_name='quote')),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved testimonials are shown publicly.', verbose_name='approved')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
