# Generated by Django 5.2.11 on 2026-02-22 21:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Business Cards, Flyers', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='Unique per shop (or globally when shop is null).', max_length=100, verbose_name='slug')),
                ('icon_svg_path', models.TextField(blank=True, help_text='Inline SVG path for the filter icon.', verbose_name='icon SVG path')),
                ('description', models.TextField(blank=True, help_text='Category description for customers', verbose_name='description')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which category appears in listings', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(blank=True, help_text='Shop that owns this category. Null = global/system category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_categories', to='shops.shop')),
            ],
            options={
                'verbose_name': 'template category',
                'verbose_name_plural': 'template categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(help_text='e.g., Premium Business Cards', max_length=200, verbose_name='title')),
                ('slug', models.SlugField(blank=True, help_text='Unique per shop (or globally when shop is null).', max_length=200, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Detailed description for customers', verbose_name='description')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Starting price for display (e.g., KES 1,200)', max_digits=10, verbose_name='starting price')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum order quantity', verbose_name='minimum quantity')),
                ('min_gsm', models.PositiveIntegerField(blank=True, help_text='Minimum paper weight allowed (e.g., 130)', null=True, verbose_name='minimum GSM')),
                ('max_gsm', models.PositiveIntegerField(blank=True, help_text='Maximum paper weight allowed (e.g., 400)', null=True, verbose_name='maximum GSM')),
                ('final_width', models.DecimalField(blank=True, decimal_places=2, help_text='Final product width in mm', max_digits=10, null=True, verbose_name='width (mm)')),
                ('final_height', models.DecimalField(blank=True, decimal_places=2, help_text='Final product height in mm', max_digits=10, null=True, verbose_name='height (mm)')),
                ('default_gsm', models.PositiveIntegerField(blank=True, help_text='Default paper weight (e.g., 300)', null=True, verbose_name='default GSM')),
                ('default_print_sides', models.CharField(choices=[('SIMPLEX', 'Single-sided'), ('DUPLEX', 'Double-sided')], default='DUPLEX', max_length=10, verbose_name='default print sides')),
                ('ups_per_sheet', models.PositiveIntegerField(blank=True, help_text='Imposition: how many finished units fit on one sheet (N-Up). Used for sheets_needed calculation.', null=True, verbose_name='units per sheet')),
                ('preview_image', models.ImageField(blank=True, upload_to='templates/previews/', verbose_name='preview image')),
                ('dimensions_label', models.CharField(help_text='e.g., 90 × 55 mm', max_length=50, verbose_name='dimensions label')),
                ('weight_label', models.CharField(help_text='e.g., 350gsm', max_length=50, verbose_name='weight label')),
                ('is_popular', models.BooleanField(default=False, verbose_name='popular')),
                ('is_best_value', models.BooleanField(default=False, verbose_name='best value')),
                ('is_new', models.BooleanField(default=False, verbose_name='new')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='meta description')),
                ('shop', models.ForeignKey(blank=True, help_text='Shop that owns this template. Null = global/system template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_templates', to='shops.shop')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_templates', to='templates.templatecategory')),
            ],
            options={
                'verbose_name': 'print template',
                'verbose_name_plural': 'print templates',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Matt Lamination, Spot UV (fallback when finishing_service null)', max_length=100, verbose_name='finishing name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If true, this finishing is always included', verbose_name='mandatory')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this is pre-selected for optional finishing', verbose_name='selected by default')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Override per unit when finishing_service set; or sole price when null', max_digits=10, verbose_name='price adjustment')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('finishing_service', models.ForeignKey(blank=True, help_text='Shop finishing service for pricing. When null, use price_adjustment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_finishings', to='pricing.finishingservice')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_options', to='templates.printtemplate')),
            ],
            options={
                'verbose_name': 'template finishing',
                'verbose_name_plural': 'template finishings',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('option_type', models.CharField(choices=[('PAPER_GSM', 'Paper Weight (GSM)'), ('SIZE', 'Size'), ('QUANTITY', 'Quantity'), ('COLOR_MODE', 'Color Mode'), ('OTHER', 'Other')], max_length=20, verbose_name='option type')),
                ('label', models.CharField(help_text="Display label (e.g., '300 GSM', '500 pcs')", max_length=100, verbose_name='label')),
                ('value', models.CharField(help_text='Actual value for calculation', max_length=100, verbose_name='value')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price change when this option is selected', max_digits=10, verbose_name='price modifier')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='templates.printtemplate')),
            ],
            options={
                'verbose_name': 'template option',
                'verbose_name_plural': 'template options',
                'ordering': ['option_type', 'display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='templatecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('slug',), name='unique_global_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='templatecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', False)), fields=('shop', 'slug'), name='unique_shop_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('slug',), name='unique_global_template_slug'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', False)), fields=('shop', 'slug'), name='unique_shop_template_slug'),
        ),
    ]
