# Generated by Django 5.2 on 2026-02-02 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Business Cards, Flyers', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('icon_svg_path', models.TextField(blank=True, help_text='Inline SVG path for the filter icon.', verbose_name='icon SVG path')),
            ],
            options={
                'verbose_name': 'template category',
                'verbose_name_plural': 'template categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(help_text='e.g., Premium Business Cards', max_length=200, verbose_name='title')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='e.g., KES 1,200', max_digits=10, verbose_name='base price')),
                ('preview_image', models.ImageField(blank=True, upload_to='templates/previews/', verbose_name='preview image')),
                ('is_popular', models.BooleanField(default=False, verbose_name='popular')),
                ('is_best_value', models.BooleanField(default=False, verbose_name='best value')),
                ('dimensions_label', models.CharField(help_text='e.g., 90 × 55 mm', max_length=50, verbose_name='dimensions label')),
                ('weight_label', models.CharField(help_text='e.g., 350gsm', max_length=50, verbose_name='weight label')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_templates', to='templates.templatecategory')),
            ],
            options={
                'verbose_name': 'print template',
                'verbose_name_plural': 'print templates',
                'ordering': ['category', 'title'],
            },
        ),
    ]
