# Generated by Django 5.2 on 2026-02-04 21:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'template category', 'verbose_name_plural': 'template categories'},
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='default_gsm',
            field=models.PositiveIntegerField(blank=True, help_text='Default paper weight (e.g., 300)', null=True, verbose_name='default GSM'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='default_print_sides',
            field=models.CharField(choices=[('SIMPLEX', 'Single-sided'), ('DUPLEX', 'Double-sided')], default='DUPLEX', max_length=10, verbose_name='default print sides'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description for customers', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='final_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final product height in mm', max_digits=10, null=True, verbose_name='height (mm)'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='final_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final product width in mm', max_digits=10, null=True, verbose_name='width (mm)'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='new'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum order quantity', verbose_name='minimum quantity'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description for customers', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which category appears in listings', verbose_name='display order'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Starting price for display (e.g., KES 1,200)', max_digits=10, verbose_name='starting price'),
        ),
        migrations.CreateModel(
            name='TemplateFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Matt Lamination, Spot UV', max_length=100, verbose_name='finishing name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If true, this finishing is always included', verbose_name='mandatory')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this is pre-selected for optional finishing', verbose_name='selected by default')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cost per unit (0 if included in base)', max_digits=10, verbose_name='price adjustment')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_options', to='templates.printtemplate')),
            ],
            options={
                'verbose_name': 'template finishing',
                'verbose_name_plural': 'template finishings',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('option_type', models.CharField(choices=[('PAPER_GSM', 'Paper Weight (GSM)'), ('SIZE', 'Size'), ('QUANTITY', 'Quantity'), ('COLOR_MODE', 'Color Mode'), ('OTHER', 'Other')], max_length=20, verbose_name='option type')),
                ('label', models.CharField(help_text="Display label (e.g., '300 GSM', '500 pcs')", max_length=100, verbose_name='label')),
                ('value', models.CharField(help_text='Actual value for calculation', max_length=100, verbose_name='value')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price change when this option is selected', max_digits=10, verbose_name='price modifier')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='templates.printtemplate')),
            ],
            options={
                'verbose_name': 'template option',
                'verbose_name_plural': 'template options',
                'ordering': ['option_type', 'display_order'],
            },
        ),
    ]
