# Generated by Django 5.2 on 2026-02-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_template_ownership_and_paper_constraints'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='allowed_gsm_values',
            field=models.JSONField(blank=True, help_text='Optional list of allowed GSM values (e.g., [250, 300, 350])', null=True, verbose_name='allowed GSM values'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='created_by_shop',
            field=models.ForeignKey(blank=True, help_text='Shop/company that created this template (for gallery display)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='shops.shop', verbose_name='created by shop'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='max_gsm',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed paper weight (e.g., 200 for flyers)', null=True, verbose_name='maximum GSM'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='min_gsm',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum allowed paper weight (e.g., 250 for business cards)', null=True, verbose_name='minimum GSM'),
        ),
    ]
