# Generated by Django 5.2.4 on 2026-02-20 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('templates', '0002_add_ups_per_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='max_gsm',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum paper weight allowed (e.g., 400)', null=True, verbose_name='maximum GSM'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='min_gsm',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum paper weight allowed (e.g., 130)', null=True, verbose_name='minimum GSM'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop that owns this template. Null = global/system template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_templates', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop that owns this category. Null = global/system category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_categories', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique per shop (or globally when shop is null).', max_length=200, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='slug',
            field=models.SlugField(help_text='Unique per shop (or globally when shop is null).', max_length=100, verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('slug',), name='unique_global_template_slug'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', False)), fields=('shop', 'slug'), name='unique_shop_template_slug'),
        ),
        migrations.AddConstraint(
            model_name='templatecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('slug',), name='unique_global_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='templatecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', False)), fields=('shop', 'slug'), name='unique_shop_category_slug'),
        ),
    ]
