# Generated by Django 5.2 on 2026-01-25 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text="Internal identifier, e.g., 'Xerox Versant 80'.", max_length=150, verbose_name='machine name')),
                ('type', models.CharField(choices=[('DIGITAL_PRINTER', 'Digital Printer (Laser/Inkjet)'), ('LARGE_FORMAT', 'Large Format Printer'), ('PLOTTER', 'Plotter / Cutter'), ('OFFSET', 'Offset Press'), ('FINISHING', 'Finishing Equipment')], default='DIGITAL_PRINTER', max_length=30, verbose_name='machine type')),
                ('is_active', models.BooleanField(default=True, help_text='If false, this machine will not be available for new jobs.', verbose_name='active')),
                ('shop', models.ForeignKey(help_text='The shop that owns this machine.', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='shops.shop')),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('feed_type', models.CharField(choices=[('SHEET_FED', 'Sheet Fed'), ('ROLL_FED', 'Roll Fed'), ('FLATBED', 'Flatbed')], default='SHEET_FED', max_length=20, verbose_name='feed type')),
                ('max_width', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum printable width in millimeters.', max_digits=10, null=True, verbose_name='max width (mm)')),
                ('max_height', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum printable height (length) in millimeters. Leave blank for unlimited rolls.', max_digits=10, null=True, verbose_name='max height (mm)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='inventory.machine')),
            ],
            options={
                'verbose_name': 'machine capability',
                'verbose_name_plural': 'machine capabilities',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text="e.g., 'Gloss Paper 300gsm'", max_length=150, verbose_name='material name')),
                ('type', models.CharField(choices=[('SHEET', 'Sheet (Paper/Card)'), ('ROLL', 'Roll (Vinyl/Banner/Canvas)'), ('RIGID', 'Rigid (Foamex/Dibond/Acrylic)')], default='SHEET', max_length=20, verbose_name='material type')),
                ('cost_per_unit', models.DecimalField(decimal_places=4, help_text='The cost price the shop pays for this material based on the unit type.', max_digits=14, verbose_name='cost per unit')),
                ('unit_type', models.CharField(choices=[('PER_SHEET', 'Per Sheet'), ('PER_SQ_METER', 'Per Square Meter'), ('PER_LINEAR_METER', 'Per Linear Meter')], default='PER_SHEET', max_length=20, verbose_name='cost unit')),
                ('is_active', models.BooleanField(default=True, help_text='If false, this material is unavailable for new calculations.', verbose_name='active')),
                ('shop', models.ForeignKey(help_text='The shop that owns this material definition.', on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='shops.shop')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('label', models.CharField(help_text="e.g., 'SRA3', '1370mm Roll', '4x8ft Sheet'", max_length=100, verbose_name='label')),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in millimeters.', max_digits=10, verbose_name='width (mm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in millimeters. Leave empty for Rolls.', max_digits=10, null=True, verbose_name='height (mm)')),
                ('current_stock_level', models.IntegerField(default=0, help_text='Current quantity on hand (sheets or full rolls).', verbose_name='current stock')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variants', to='inventory.material')),
            ],
            options={
                'verbose_name': 'material stock',
                'verbose_name_plural': 'material stocks',
                'ordering': ['label'],
            },
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_machine_name_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_material_name_per_shop'),
        ),
    ]
