# Generated by Django 5.2 on 2026-02-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Xerox Versant 80', max_length=150, verbose_name='machine name')),
                ('machine_type', models.CharField(choices=[('DIGITAL', 'Digital Printer'), ('LARGE_FORMAT', 'Large Format'), ('OFFSET', 'Offset Press'), ('FINISHING', 'Finishing Equipment')], default='DIGITAL', max_length=20, verbose_name='type')),
                ('max_paper_width', models.PositiveIntegerField(blank=True, help_text='Maximum paper width this machine can handle', null=True, verbose_name='max width (mm)')),
                ('max_paper_height', models.PositiveIntegerField(blank=True, help_text='Maximum paper height this machine can handle', null=True, verbose_name='max height (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='shops.shop')),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('feed_type', models.CharField(choices=[('SHEET_FED', 'Sheet Fed'), ('ROLL_FED', 'Roll Fed'), ('FLATBED', 'Flatbed')], default='SHEET_FED', max_length=20)),
                ('max_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='inventory.machine')),
            ],
            options={
                'verbose_name': 'machine capability (legacy)',
                'verbose_name_plural': 'machine capabilities (legacy)',
            },
        ),
        migrations.CreateModel(
            name='PaperStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5 (148 × 210 mm)'), ('A4', 'A4 (210 × 297 mm)'), ('A3', 'A3 (297 × 420 mm)'), ('SRA3', 'SRA3 (320 × 450 mm)'), ('SRA4', 'SRA4 (225 × 320 mm)')], default='SRA3', max_length=20, verbose_name='paper size')),
                ('gsm', models.PositiveIntegerField(help_text='Paper weight: 80, 130, 150, 200, 300, etc.', verbose_name='GSM (weight)')),
                ('paper_type', models.CharField(choices=[('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('BOND', 'Bond'), ('ART', 'Art Paper')], default='GLOSS', max_length=20, verbose_name='paper type')),
                ('width_mm', models.PositiveIntegerField(help_text='Width in millimeters', verbose_name='width (mm)')),
                ('height_mm', models.PositiveIntegerField(help_text='Height in millimeters', verbose_name='height (mm)')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, help_text='Number of sheets currently in stock', verbose_name='quantity in stock')),
                ('reorder_level', models.PositiveIntegerField(default=100, help_text='Order more when stock falls below this level', verbose_name='reorder level')),
                ('buying_price_per_sheet', models.DecimalField(blank=True, decimal_places=2, help_text='Your cost per sheet', max_digits=10, null=True, verbose_name='buying price per sheet')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_stock', to='shops.shop')),
            ],
            options={
                'verbose_name': 'paper stock',
                'verbose_name_plural': 'paper stocks',
                'ordering': ['sheet_size', 'gsm'],
            },
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_machine_name_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='paperstock',
            constraint=models.UniqueConstraint(fields=('shop', 'sheet_size', 'gsm', 'paper_type'), name='unique_paper_stock'),
        ),
    ]
