# Generated by Django 5.2.11 on 2026-02-22 21:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='e.g., Xerox Versant 80', max_length=150, verbose_name='machine name')),
                ('machine_type', models.CharField(choices=[('DIGITAL', 'Digital Printer'), ('LARGE_FORMAT', 'Large Format'), ('OFFSET', 'Offset Press'), ('FINISHING', 'Finishing Equipment')], default='DIGITAL', max_length=20, verbose_name='type')),
                ('max_paper_width', models.PositiveIntegerField(blank=True, help_text='Maximum paper width this machine can handle', null=True, verbose_name='max width (mm)')),
                ('max_paper_height', models.PositiveIntegerField(blank=True, help_text='Maximum paper height this machine can handle', null=True, verbose_name='max height (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='shops.shop')),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'name'), name='unique_machine_name_per_shop')],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A5', 'A5 (148 × 210 mm)'), ('A4', 'A4 (210 × 297 mm)'), ('A3', 'A3 (297 × 420 mm)'), ('SRA3', 'SRA3 (320 × 450 mm)'), ('SRA4', 'SRA4 (225 × 320 mm)')], default='SRA3', max_length=20, verbose_name='paper size')),
                ('gsm', models.PositiveIntegerField(help_text='Paper weight: 80, 130, 150, 200, 300, etc.', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(500)], verbose_name='GSM (weight)')),
                ('paper_type', models.CharField(choices=[('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('BOND', 'Bond'), ('ART', 'Art Paper')], default='GLOSS', max_length=20, verbose_name='paper type')),
                ('width_mm', models.PositiveIntegerField(blank=True, help_text='Width in millimeters (auto-filled)', null=True, verbose_name='width (mm)')),
                ('height_mm', models.PositiveIntegerField(blank=True, help_text='Height in millimeters (auto-filled)', null=True, verbose_name='height (mm)')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='What YOU pay per sheet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='buying price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='What CUSTOMER pays per sheet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='selling price')),
                ('quantity_in_stock', models.PositiveIntegerField(blank=True, default=0, help_text='Number of sheets in stock (optional)', null=True, verbose_name='quantity in stock')),
                ('reorder_level', models.PositiveIntegerField(blank=True, default=100, help_text='Order more when stock falls below this (optional)', null=True, verbose_name='reorder level')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default_seeded', models.BooleanField(default=False, verbose_name='default seeded')),
                ('needs_review', models.BooleanField(default=False, verbose_name='needs review')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='shops.shop')),
            ],
            options={
                'verbose_name': 'paper',
                'verbose_name_plural': 'papers',
                'ordering': ['sheet_size', 'gsm'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'sheet_size', 'gsm', 'paper_type'), name='unique_paper')],
            },
        ),
    ]
